build:
  version: "1.0"

accounts:
  message: "Welcome to Nakoual accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@nakoual.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345